[test]
coverage = true
coverageSkipTestFiles = true
coveragePathIgnorePatterns = [
  "dist/**",
  "src/commands/exportPagesAndComponents.ts",
  "src/commands/devup/import-devup.ts",
  "src/commands/devup/export-devup.ts",
  "src/codegen/responsive/index.ts",
]
coverageThreshold = 1
