export const PAGE_DEVUP_DESIGN_SYSTEM = 'Devup Design System'
export const FRAME_DEVUP_COLOR_PALETTE = 'Devup Color Palette'

// 색 변경시 대상 변수를 찾기 위한 키
export const DATA_DEVUP_COLORS_VAR = 'DEVUP_COLORS_VAR'
export const DATA_DEVUP_COLORS_VAR_MODE_ID = 'DEVUP_COLORS_VAR_MODE_ID'
export const DATA_DEVUP_COLORS_VAR_MODE = 'DEVUP_COLORS_VAR_MODE'

export const DATA_DEVUP_COLORS_KEY = 'DEVUP_COLORS_KEY'
export const DATA_DEVUP_COLORS_VALUE = 'DEVUP_COLORS_VALUE'
export const DATA_DEVUP_DARK_COLORS_VALUE = 'DEVUP_DARK_COLORS_VALUE'
